@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTIxNzI3MTEsIm5hbWUiOiJtYWRkaW4xIn0.W9bfUq5xFLR5bWbZ79unNmkJDVHd4s672B4ZDaNrDQg

### Testing fiber
GET http://127.0.0.1:3000/ HTTP/1.1

### Testing fiber
GET http://127.0.0.1:3000/ping HTTP/1.1

### Testing fiber
GET http://127.0.0.1:3000/api HTTP/1.1

### Testing fiber
POST http://127.0.0.1:3000/api/auth/create HTTP/1.1
content-type: application/json

{
   "username": "maddin1",
   "password": "test1234"
}


### Testing fiber
POST http://127.0.0.1:3000/api/auth/login HTTP/1.1
content-type: application/json

{
   "identity": "maddin1",
   "password": "test1234"
}

### Testing fiber
GET http://127.0.0.1:3000/api/trk/whoami HTTP/1.1
Authorization: Bearer {{token}}

### Testing fiber
GET http://127.0.0.1:3000/api/trk/list/all HTTP/1.1
Authorization: Bearer {{token}}

### Testing fiber
GET http://127.0.0.1:3000/api/trk/ HTTP/1.1
Authorization: Bearer {{token}}


### Testing fiber
GET http://127.0.0.1:3000/api/trk/list/date/2022-02-26 HTTP/1.1
Authorization: Bearer {{token}}

### Send a new Timestamp to the backend
POST http://127.0.0.1:3000/api/trk/submit HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}


{
   "time": "2022-02-27T11:24:30+01:00",
   "isCheckin": false,
   "category": "default"
}

### Send a new Timestamp to the backend
POST http://127.0.0.1:3000/api/trk/delete/7ec81c9e-f9c5-48d2-bc21-2b97e81c17c7 HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

### Delete TS by ID
POST http://127.0.0.1:3000/api/trk/delete/10 HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}


### Get a summary for a specific Day e.g. 2022-02-15
GET http://127.0.0.1:3000/api/trk/summary/date/2022-02-27 HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}


